var filme = 'Titanic';
var series = "Stranger things";
var poema = " Lorem ipsum dolor sit amet \nconsectetur adipisicing elit. \nCum labore ab veritatis dignissimos \nipsum recusandae necessitatibus porro \nearum reiciendis ex accusantium, atque, \nnihil doloribus corporis consectetur inventore \nunde. Quibusdam, itaque!";
var programas1 = "Mis programas favoritos son: " + filme + " y " + series;
console.log(programas1);
var programas = "Mis programas favoritos son: " + filme + " y " + series;
console.log(programas);
var edad_actual = 42;
var edad_futura = "\n\n    En Abril mi edad sera de: " + (edad_actual + 1) + "\n\n";
console.log(edad_futura);
console.log(programas.charAt(0));
console.log(programas.toUpperCase());
